-- MySQL Script generated by MySQL Workbench
-- Tue Jun 25 09:21:57 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 2024calebwormald
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `2024calebwormald` DEFAULT CHARACTER SET utf8;
USE `2024calebwormald`;

-- -----------------------------------------------------
-- Table `2024calebwormald`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `2024calebwormald`.`User`;

CREATE TABLE IF NOT EXISTS `2024calebwormald`.`User` (
  `user_id` INT AUTO_INCREMENT,
  `first_name` VARCHAR(45),
  `last_name` VARCHAR(45),
  `email` VARCHAR(45),
  `phone_number` VARCHAR(45),
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `2024calebwormald`.`Alumni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `2024calebwormald`.`Alumni`;

CREATE TABLE IF NOT EXISTS `2024calebwormald`.`Alumni` (
  `alumni_id` INT AUTO_INCREMENT,
  `User_user_id` INT NOT NULL,
  `graduation_year` YEAR(4),
  PRIMARY KEY (`alumni_id`),
  INDEX `fk_Alumni_User1_idx` (`User_user_id` ASC),
  CONSTRAINT `fk_Alumni_User1`
    FOREIGN KEY (`User_user_id`)
    REFERENCES `Reunion`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `2024calebwormald`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `2024calebwormald`.`Order`;

CREATE TABLE IF NOT EXISTS `2024calebwormald`.`Order` (
  `order_id` INT AUTO_INCREMENT,
  `customer_id` INT,
  `order_date` DATE,
  `total_amount` DECIMAL(10, 2),
  `status` VARCHAR(45),
  PRIMARY KEY (`order_id`)
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `2024calebwormald`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `2024calebwormald`.`Customer`;

CREATE TABLE IF NOT EXISTS `2024calebwormald`.`Customer` (
  `customer_id` INT AUTO_INCREMENT,
  `User_user_id` INT NOT NULL,
  INDEX `fk_Customer_User1_idx` (`User_user_id` ASC),
  PRIMARY KEY (`customer_id`),
  CONSTRAINT `fk_Customer_User1`
    FOREIGN KEY (`User_user_id`)
    REFERENCES `Reunion`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `2024calebwormald`.`Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `2024calebwormald`.`Event`;

CREATE TABLE IF NOT EXISTS `2024calebwormald`.`Event` (
  `event_id` INT AUTO_INCREMENT,
  `name` VARCHAR(45),
  `date` DATE,
  `location` VARCHAR(45),
  `description` TEXT,
  PRIMARY KEY (`event_id`)
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `2024calebwormald`.`RSVP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `2024calebwormald`.`RSVP`;

CREATE TABLE IF NOT EXISTS `2024calebwormald`.`RSVP` (
  `rsvp_id` INT AUTO_INCREMENT,
  `alumni_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  `response` TINYINT,
  `guest_count` INT,
  PRIMARY KEY (`rsvp_id`),
  INDEX `fk_RSVP_Event1_idx` (`event_id` ASC),
  INDEX `fk_RSVP_Alumni1_idx` (`alumni_id` ASC),
  CONSTRAINT `fk_RSVP_Event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `Reunion`.`Event` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RSVP_Alumni1`
    FOREIGN KEY (`alumni_id`)
    REFERENCES `Reunion`.`Alumni` (`alumni_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `2024calebwormald`.`ProductCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `2024calebwormald`.`ProductCategory`;

CREATE TABLE IF NOT EXISTS `2024calebwormald`.`ProductCategory` (
  `category_id` INT AUTO_INCREMENT,
  `category_name` VARCHAR(45),
  `description` TEXT,
  PRIMARY KEY (`category_id`)
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `2024calebwormald`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `2024calebwormald`.`Product`;

CREATE TABLE IF NOT EXISTS `2024calebwormald`.`Product` (
  `product_id` INT AUTO_INCREMENT,
  `ProductCategory_category_id` INT NOT NULL,
  `name` VARCHAR(45),
  `description` TEXT,
  `price` DECIMAL(10, 2),
  `stock` INT,
  `image` VARCHAR(255),
  PRIMARY KEY (`product_id`),
  INDEX `fk_Product_ProductCategory1_idx` (`ProductCategory_category_id` ASC),
  CONSTRAINT `fk_Product_ProductCategory1`
    FOREIGN KEY (`ProductCategory_category_id`)
    REFERENCES `Reunion`.`ProductCategory` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `2024calebwormald`.`Order_Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `2024calebwormald`.`Order_Item`;

CREATE TABLE IF NOT EXISTS `2024calebwormald`.`Order_Item` (
  `order_item_id` INT AUTO_INCREMENT,
  `Order_order_id` INT NOT NULL,
  `Product_product_id` INT NOT NULL,
  `quantity` INT,
  `price` DECIMAL(10, 2),
  PRIMARY KEY (`order_item_id`),
  INDEX `fk_Order_Item_Order1_idx` (`Order_order_id` ASC),
  INDEX `fk_Order_Item_Product1_idx` (`Product_product_id` ASC),
  CONSTRAINT `fk_Order_Item_Order1`
    FOREIGN KEY (`Order_order_id`)
    REFERENCES `Reunion`.`Order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Item_Product1`
    FOREIGN KEY (`Product_product_id`)
    REFERENCES `Reunion`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `2024calebwormald`.`Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `2024calebwormald`.`Payment`;

CREATE TABLE IF NOT EXISTS `2024calebwormald`.`Payment` (
  `payment_id` INT AUTO_INCREMENT,
  `Order_order_id` INT NOT NULL,
  `payment_date` DATE,
  `amount` DECIMAL(10, 2),
  `payment_method` VARCHAR(45),
  PRIMARY KEY (`payment_id`),
  INDEX `fk_Payment_Order1_idx` (`Order_order_id` ASC),
  CONSTRAINT `fk_Payment_Order1`
    FOREIGN KEY (`Order_order_id`)
    REFERENCES `Reunion`.`Order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB;

-- Reset foreign key checks and unique checks
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
